{% set name = "pytao" %}
{% set version = "0.5.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc464aab8169aea26e5e57ebb98a14f1768e10c0c730715d0e97523212e8de1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >={{ python_min }}
    - bmad >=20250925
    - h5py
    - matplotlib-base
    - numpy
    - pexpect
    - pydantic >=2
    - tqdm

test:
  requires:
    - python {{ python_min }}
    - git
    - pytest
    - pytest-cov
    - bokeh
    - ipython
    - openpmd-beamphysics
  imports:
    - pytao
    - pytao.plotting
    - pytao.plotting.bokeh
  commands:
    # Add back once https://github.com/bmad-sim/pytao/issues/101 is resolved:
    # - pytao --help
    - test -f $PREFIX/bin/pytao-gui  # [unix]
    - git clone --depth 1 https://github.com/bmad-sim/bmad-ecosystem bmad
    - echo | pytao -noplot -lat $PWD/bmad/bmad-doc/tao_examples/erl/lat.bmad
    - TAO_REUSE_SUBPROCESS=1 ACC_ROOT_DIR=$PWD/bmad pytest -v --pyargs pytao.tests -k "not help and not test_plot"

about:
  home: https://github.com/bmad-sim/pytao
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
  description: |
    PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
    Tao is an open source general purpose program for charged particle and X-ray simulations in 
    accelerators and storage rings.
  doc_url: https://bmad-sim.github.io/pytao
  dev_url: https://github.com/bmad-sim/pytao

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
    - ken-lauer
